### ISSUE TITLE
Tracking issue: Delendum benchmarks project

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/examples#10]
### Goal(s)
- Benchmark Miden VM against the defined scenarios in https://github.com/delendum-xyz/zk-benchmarking
- Add necessary features and change code to be able to benchmark

### Details
For this target, we want to benchmark the Miden VM against other proving systems, e.g. Risk0. Therefore, we have predefined scenarios. Our goal is to create a neutral and objective playground to benchmark several proving systems also to invite other systems like Cairo VM in the future.

```[tasklist]

### Must have

- [x] #9 
- [x] #12
- [x] #13
- [x] #14 
- [x] #30 
- [x] #31 
```

```[tasklist]

### Nice to have

- [ ] #15
```

## Working group:
@Dominik1999 @itzmeanjan 

<details>
<summary>Workflow</summary>

- Discussion should happen here or in the related sub-issues.
- PRs should only be merged by the coordinator, to ensure everyone is able to review.
- Aim to complete reviews within 24 hours.
- When a related sub-issue is opened:
    - add it to the list of sub-issues in this tracking issue
- When opening a related PR:
    - request review from everyone in this working group
- When a sub-issue is completed:
    - close the related issue with a comment that links to the PR where the work was completed
</details>

### Coordinator: @Dominik1999 

<details>
<summary>Workflow</summary>

The working group coordinator ensures scope & progress tracking are transparent and accurate. They will:

- Merge approved PRs after all working group members have completed their reviews.
    - add the PR # to the relevant section of the current tracking PR.
    - close any completed sub-issue(s) with a comment that links to the PR where the work was completed
- Monitor workflow items and complete anything that slips through the cracks.
- Monitor scope to see if anything is untracked or unclear. Create missing sub-issues or initiate discussion as required.
- Monitor progress to see if there's anything which isn't moving forward. Initiate discussion as required.
- Identify PRs with especially significant changes and add @grjte and @bobbinth for review.
</details>

**Comment by bobbinth** [comment]
I would also add benchmarks for hash chain and Merkle path verification using Rescue Prime.

**Comment by bobbinth** [comment]
I would say hash chain using BLAKE3, SHA256, and Rescue Prime is a "must have" and things beyond that (e.g., Merkle Path verification) are "nice to have" for now.

**Comment by Dominik1999** [comment]
So for the Delendum Project, we now have decided to start with a scenario of a hash chain using the natural hash functions. In our case that would be Rescue Prime.

**Comment by bobbinth** [comment]
I would still benchmark all 3 functions listed above, I think it would be much more informative than benchmarking native functions.

**Comment by itzmeanjan** [comment]
> I would still benchmark all 3 functions listed above, I think it would be much more informative than benchmarking native functions.

Agreed, benchmarking only Rescue Prime won't give us full picture of the stage. I think we should keep 

- Blake3
- SHA256
- Rescue Prime
- Keccak256

In above list, except using Keccak256, we've ability to hash both 32/ 64 -bytes input.

**Comment by Dominik1999** [comment]
Got it, in the Delendum project we can now benchmark Rescue Prime, Sha256, Blake3. 

I am unsure in which cases a developer would not use the "natural" hash function. I think, in the case for the final proof that is being put the Ethereum it is necessary to use Keccak. But besides that, are there significant security differences?

**Comment by bobbinth** [comment]
Developers will likely use native hash function as frequently as possible. The main purpose for benchmarking other hash functions is to shows how the VM can handle complex computations which it wasn't optimized for. Basically, we use non-native hash functions as a sort of a proxy for other complex computations.

**Comment by Dominik1999** [comment]
got it

**Comment by Dominik1999** [comment]
We decided to pause the second scenario for now. RISC Zero is not having it yet and we can pick it up later.
