### ISSUE TITLE
Change repo structure and put playground into own folder

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/examples#11]
One other comment: I wonder whether rather than putting the playground into the root of the repo it should go into something like `/wasm-playground` (or just `/playground`) directory. This would enable us to add other things in the future (e.g., CLI mentioned in #9). Maybe the structure of the repo could be something like:

```
├─ bench-cli
├─ examples
└─ playground
```

What do you guys think?

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/examples/issues/6#issuecomment-1326857075_

**Comment by grjte** [comment]
Once we do this, let's also see about deploying the playground to https://0xpolygonmiden.github.io/playground instead of to `examples`

**Comment by bobbinth** [comment]
Should we try to put this under a custom domain? Something like `miden.polygon.technology/vm-playground`

**Comment by grjte** [comment]
Yes, we could change the domain in the settings easily, and I think `miden.polygon.technology` would be good. The path would still depend on these changes though. I prefer `playground` to `vm-playground`

Also, I would prefer to complete this issue before releasing v0.1. What do you think?
