### ISSUE TITLE
Implement 1-to-1 hashing for Sha256 module in Miden `stdlib`

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/examples#13]
Currently, we can hash using Sha256; see [here](https://maticnetwork.github.io/miden/user_docs/stdlib/crypto/hashes.html). This hash has 64-bytes as input and 32-bytes as output.

However, when we want to compute multiple hashes in a row, e.g. hash(hash(a,b), b)) or hash(hash(a,b)), we need the ability to hash using a 32-byte input as well.

**Comment by itzmeanjan** [comment]
I've written routine for computing SHA256 over 32 -bytes input, see https://github.com/maticnetwork/miden/pull/565

**Comment by bobbinth** [comment]
Closed by https://github.com/maticnetwork/miden/pull/565
