### ISSUE TITLE
Proving toast doesn't close after failure to prove

### ISSUE THREAD

**Issue by Overcastan** [0xPolygonMiden/examples#136]
Inputs: 
```
{
    "operand_stack": ["1", "1"]
}
```
Assembly code:
```
begin
    repeat.99999
        swap 
        dup.1 
        add
    end
end
```

Using modified fibonacci code with `99999` as a repeat number results in `Error: RuntimeError: unreachable`. But the problem is that after this failure `Proving ...` toast notification window remains on screen.

**Comment by Dominik1999** [comment]
This bug doesn't exist anymore
