### ISSUE TITLE
Benchmarking 1: Create a hash chain scenario for Rescue Prime of 1, 10, 100, and 1000 hashes

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/examples#14]
For the Delendum Benchmarking project our first benchmarking scenario will be to iterate a hash function - which we call a hash chain. We will iterate our default hash function Rescue Prime. 

The scenario is defined as 

Compute `h(h(h(...h(x))))`, where `h()` is a cryptographic hash function for some input `[0u8; 32]` (32-bytes).

We will benchmark three different chain lengths, 1, 10 and 100 hashes. 

The benchmarking repo can be found here. https://github.com/delendum-xyz/zk-benchmarking

Steps: 

- [x] create 1-to-1 Rescue Prime
- [x] create scenario for hash chains
- [x] measure time to prove
- [x] measure time to proof size
- [x] measure time to verify
- [x] check result according to hash function

PR is here https://github.com/delendum-xyz/zk-benchmarking/pull/5

**Comment by itzmeanjan** [comment]
I just wrote assembly routine for computing Rescue Prime digest over 32 -bytes input. See https://github.com/maticnetwork/miden/pull/576

**Comment by bobbinth** [comment]
I think we need to compute a hash chain, we could do it more efficiently than using a general 1x1 hashing. For example, let's assume we have 4 elements on the stack which are the start of the hash chain (the seed) and that we want to hash it 100 times. The code could look like this:

```
# stack start: [a3, a2, a1, a0, ...]
push.4.0.0.0
mem_storew.0 # save [4, 0, 0, 0] into memory location 0
swapw
push.0.0.0.0 # => stack state [0, 0, 0, 0, a3, a2, a1, a0, 0, 0, 0, 4, ...]

# compute hash chain
repeat.100
    rpperm
    mem_loadw.0 # overwrite the top word with [4, 0, 0, 0]
    swapw2
    mem_loadw.1 # overwrite top word with [0, 0, 0, 0]
end

# drop everything but the digest from the stack
dropw
swapw
dropw
```
This whole thing should take about 720 cycles vs. the approach with general 1x1 hash which would take 2100+ cycles.

**Comment by bobbinth** [comment]
Actually, the above will probably take closer to 1100 cycles as just 100 hashes will require 800 rows in the hasher chiplet + we need 200 memory accesses, ~100 rows for hashing the program itself.

**Comment by itzmeanjan** [comment]
Yes makes sense, much better way to solve this. Though we may consider to expose an API for hashing 32 -bytes ( 4 field elements ), for which we can keep https://github.com/maticnetwork/miden/pull/576.

**Comment by Dominik1999** [comment]
When I use the above program, I get

```
thread 'main' panicked at 'Could not compile source: ParsingError("instruction 'swapw2' is invalid")', src/benches/iter_rescue_prime.rs:67:14
```

Can you provide such a program as @bobbinth sketches using your 1-to-1 RP hash @itzmeanjan ?

I would want to include it right here using the defined input `vec![0_u8, 32]` as `stack_init`

**Comment by bobbinth** [comment]
There is a typo - `swapw2` should be `swapw.2`.

**Comment by Dominik1999** [comment]
Maybe we can talk about Program 1 @itzmeanjan and see how we can write it such that it creates the most optimal hash chain for the given input `[0u8; 32]`? Do you have an idea?

**Comment by bobbinth** [comment]
> I removed the `push.4.0.0.0` because we wanted to benchmark the systems using an external input of `vec![0_u8, 32]`. I am not sure if it makes a difference.

We can't do this. These are not a part of the input - these are needed to initialize capacity portion of the hasher state.

> Program 1 takes a bit longer to be executed and proven

This is likely because the number of cycles for both programs gets rounded to the same power of two. Using back-of-the-envelope computations I get, for 1000 iterations:

- Program 1: 1.1M cycles
- Program 2: 1.9M cycles

But both of them get rounded to the next power of two which is about 2M cycles. This happens because trace length must always be a power of two.

**Comment by bobbinth** [comment]
> > I removed the `push.4.0.0.0` because we wanted to benchmark the systems using an external input of `vec![0_u8, 32]`. I am not sure if it makes a difference.
> 
> We can't do this. These are not a part of the input - these are needed to initialize capacity portion of the hasher state.

btw, we should really add an independently-computed result to make sure the program does the right thing.

**Comment by itzmeanjan** [comment]
> I removed the `push.4.0.0.0` because we wanted to benchmark the systems using an external input of `vec![0_u8, 32]`. I am not sure if it makes a difference.

As @bobbinth said it will produce incorrect result. 

> **Note**

May be avoid optimized version that @bobbinth suggested ( in https://github.com/0xPolygonMiden/examples/issues/14#issuecomment-1335680162 ) during first time and use https://github.com/maticnetwork/miden/pull/576 which exposes an API for hashing 32 -bytes input ( i.e. 4 field elements on stack, compared to 8 of them expected by `rphash` ) --- can be better choice, because that API won't let you misuse it and it's highly likely that it will produce correct result, though it's expensive. We can use optimized version in next round.

**Comment by itzmeanjan** [comment]
@Dominik1999 [this](https://github.com/itzmeanjan/miden/blob/9092607c758183cee571713638faeab200e1fda7/stdlib/asm/crypto/hashes/rescue_prime.masm) is the version of rescue prime I mentioned in my last message.

**Comment by bobbinth** [comment]
We should use `hash_elements()` instead of `hash()` as these functions work differently when the underlying data contains valid field element. See note on hash output consistency [here](https://docs.rs/winter-crypto/0.4.2/winter_crypto/hashers/struct.Rp64_256.html#hash-output-consistency).

**Comment by Dominik1999** [comment]
Ok, so I tried three different Rescue Prime Assmebly Programs now and compared it to a **Rust Implementation**

```
    let input = vec![BaseElement::ZERO; 4];
    let h_output = Rp64_256::hash_elements(&input);
```

I get different results.

```
Rust Hashing: [2526470497159956267, 3153259110699805053, 5501098472172155749, 11330409471891329886]
Assembly Program 1: [11330409471891329886, 5501098472172155749, 3153259110699805053, 2526470497159956267]
Assembly Program 2: [11330409471891329886, 5501098472172155749, 3153259110699805053, 2526470497159956267]
Assembly Program 3: [9233990305047322442, 13303861308640222486, 13320606106853856250, 14241590595577346877]
```

Here is the gist https://gist.github.com/Dominik1999/a984156dcafdeb9fa2d602ca67e79b74

**Comment by bobbinth** [comment]
Seems everything works as expected, right? Programs 1 and 2 give the same result as Rust (the result is reversed because it is in the stack order). Program 3 gives a different result because it hashes 8 elements rather than 4 (if you were to use `let input = vec![BaseElement::ZERO; 8];` then assembly output would have been the same as Rust).

**Comment by Dominik1999** [comment]
You are right. Took me a while to remember that Assembly returns the wrong order.

**Comment by Dominik1999** [comment]
Closed in https://github.com/delendum-xyz/zk-benchmarking/pull/5
