### ISSUE TITLE
Synchronise instruction set with source code

### ISSUE THREAD

**Issue by gubloon** [0xPolygonMiden/examples#163]
In this issue, I work on a module that adds synchronisation to instruction set in a way that the data is fetched from respective source code rather than manual updation.
```[tasklist]
### Tasks
- [ ] Add macros
- [ ] Add synchroniser
- [ ] Tests - if required
```

**Comment by gubloon** [comment]
example macro(how it will look like within code):

// #Sdepth: begin 
Instruction::Sdepth => span.add_op(SDepth),
// #input: '[ ... ]'
// #output: '[d, ... ]'
// #description: '$d \\leftarrow stack.depth()$ \n \n Pushes the current depth of the stack onto the stack.'
// #Sdepth: end

**Comment by gubloon** [comment]
Below is an alternative way of the macro which includes all instructions including one macro block so that its less verbose / more simple and a new instructions can be automatically picked up:

            // #instruction: begin
            Instruction::Sdepth => span.add_op(SDepth),
            // #input: '[ ... ]'
            // #output: '[d, ... ]'
            // #description: '$d \leftarrow stack.depth()$ \n \n Pushes the current depth of the stack onto the stack.'

            Instruction::Caller => env_ops::caller(span, ctx),
            // #input: '[ ... ]'
            // #output: '[a, ... ]'
            // #description: '$H \\leftarrow context.fn\\_hash()$ \n \n Overwrites the top four stack items with the hash of a function which initiated the current SYSCALL. \n \n Executing this instruction outside of SYSCALL context will fail.'
            
            Instruction::Clk => span.add_op(Clk),
            // #input: '[ ... ]'
            // #output: '[t, ... ]'
            // #description: '$t \\leftarrow clock\\_value()$ \n \n Pushes the current value of the clock cycle counter onto the stack.'
            // #instructions: end

**Comment by Dominik1999** [comment]
That looks like what we need. In general, we need all instructions in the form of a JSON file. We can use that to build it in a cool way in the playground. Our end goal should be something like this: https://www.evm.codes/?fork=shanghai. 

This is how the team has done it here https://github.com/smlxl/evm.codes/blob/main/opcodes.json

I think as a first step, we need to define a different format for the JSON file. Like we don't have OPCODES but instructions. 

Then we could build a simple script that reads the md files from https://github.com/0xPolygonMiden/miden-vm/tree/main/docs/src/user_docs/assembly and parses the tables into our JSON format. 

Here is a simple python script (that I got from ChatGPT). But we can also ask ChatGPT directly to convert `.md`-tables into our JSON-format. We just need to ensure that we do it whenever there is a change in `main`.

```Python
import markdown2
import os
import json

instructions = []

# Loop through your markdown files
for filename in os.listdir('path/to/assembly'):
    if filename.endswith('.md'):
        with open(f'path/to/assembly/{filename}', 'r') as file:
            content = file.read()
            html = markdown2.markdown(content)

            # Extract data (this is a simplified example)
            # You need to adjust it to match the structure of your Markdown files
            name = extract_name(html)
            description = extract_description(html)
            # other fields...

            instructions.append({
                "name": name,
                "description": description,
                # other fields...
            })

# Save to a JSON file
with open('miden_vm_instructions.json', 'w') as json_file:
    json.dump(instructions, json_file, indent=4)
```
