### ISSUE TITLE
Change the UI and create our own component

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/examples#17]
For the future: It would be good to pull this out into its own component and add it at both the top and the bottom of the screen. I think that would provide better UX (people wouldn't need to scroll back up after writing their code). Do you agree? If so, can you create an issue?

_Originally posted by @grjte in https://github.com/0xPolygonMiden/examples/pull/6#discussion_r1032216601_

**Comment by Overcastan** [comment]
It seems to me that it is even more convenient to make this component in the form of a movable header, so that it always remains on top of the screen, regardless of which part of the code we are currently on.

**Comment by Dominik1999** [comment]
Closed by #47
