### ISSUE TITLE
Improve and make the mobile version more stable

### ISSUE THREAD

**Issue by gubloon** [0xPolygonMiden/examples#181]
The mobile version that we have added recently was planned ad-hoc and done in a relatively short period of time. As part of this milestone, we want to improve it with a new version that is more stable and well tested enough to make the playground ready for rollup integration.

**Comment by gubloon** [comment]
1. Visually, we want to make each page and UI elements adaptive and responsive to the mobile screen
2. Our main objective for having the mobile version is to showcase how fast Miden's proving/execution works even on a mobile device - so we want to make sure the cache handling and memory is well optimised.

**Comment by Dominik1999** [comment]
In general, we don't think many people will code Miden Assembly on their mobile phones. However, on conferences I always use a QR code in presentations. Then ppl can open the playground on their mobile phone. The goal is to show how fast the VM can prove programs on a mobile phone browser.
