### ISSUE TITLE
Show op and asmop in the DebugOutput

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/examples#82]
We don't show `op: Option<Operation>` or `asmop: Option<AsmOpInfo>` in the output. We cannot simply return `Operation` or `AsmOpInfo`, but we might be able to deserialize it.

This is not super complicated but we need to decide how we want to show it.

**Comment by hackaugusto** [comment]
@Dominik1999 could you elaborate a bit, what do you mean by show and why is that currently not possible?

**Comment by Dominik1999** [comment]
Yes, will do. This was more less a placeholder issue. Will do tonight

**Comment by Dominik1999** [comment]
Will close this now because in #79 it works
