### ISSUE TITLE
Create a small benchmarking CLI

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/examples#9]
We should add a small CLI which could be used to benchmark any of the examples. This would also be helpful for the Delendum benchmarking project.

The CLI should take a path to the example directory as input, execute/prove the example, and output the following metrics:

1. Cold compilation time (i.e., when the example is compiled with a new assembler).
2. Hot compilation time (i.e., when the example is complied with an assembler which was already used to compile the same code).
3. Execution time.
4. Proving time.
5. Verification time.

It would also be nice to enable benchmarking at 96-bit and 128-bit security levels. So, maybe this could be another input parameter for the CLI.

Lastly, it would be really nice to also have the benchmark verify the correctness of the result. The simplest way to do it would be include the expected result for a given example into the example directory. This would, however, mean that adjusting example parameters would be difficult. We could also include a small Rust file with each example which could output the expected result for a given set of parameters - but this might be something we do later on.

**Comment by Dominik1999** [comment]
We have a script for benchmarking here in the Delendum Project folder. https://github.com/delendum-xyz/zk-benchmarking

The question is, do we need our own script and the ability to benchmark in our examples-repo as well?

**Comment by bobbinth** [comment]
I think so. I took a quick look at the benchmarking program, and I don't think it has everything we need (but maybe I missed it)?

But also, it would be good to have a separate benchmark CLI which we could evolve independently in the future.

**Comment by Dominik1999** [comment]
Ok, I am on this issue now. 

Is this related to the Delendum benchmarking examples? Or do you mean the examples from the Playground?

**Comment by bobbinth** [comment]
I think this is more general - i.e., would be good to be able to benchmark all examples in this repo.

**Comment by Dominik1999** [comment]
> Lastly, it would be really nice to also have the benchmark verify the correctness of the result. The simplest way to do it would be include the expected result for a given example into the example directory. This would, however, mean that adjusting example parameters would be difficult. We could also include a small Rust file with each example which could output the expected result for a given set of parameters - but this might be something we do later on.

I think we had this before in the examples. I will create another issue to track that part.
