### ISSUE TITLE
Add syntax highlighting to the CodeEditor

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/examples#91]
We can add syntax highlighting to the code editor for MASM. 

Here is a Miden Assembly [extension for VScode](https://marketplace.visualstudio.com/items?itemName=dlock.miden-assembly). I think, we can reuse them for the CodeMirror. But I am not 100% sure. Here is some info https://codemirror.net/docs/ref/#language.syntaxHighlighting

**Comment by kaushalbhardwaj** [comment]
Solutions experimented:

Tried to use the existing VS Code extension repo and the masm.tmLanguage.json file for the language's grammar in syntax highlight of the CodeMirror package. But unable to generate the lezer grammar or unable to convert the text grammar into lezer grammar. [https://github.com/daedlock/vscode-miden-assembly/blob/main/syntaxes/masm.tmLanguage.json](Link to masm file)

Tried to use language support from code mirror for similar language but neither x86 nor assembly language was available [https://github.com/codemirror/legacy-modes/tree/main](here). 

Finally used the C language from legacy-modes for the support and it works well for our case.

The only improvement we can make is adding language grammar but not a necessity. The current one also works well.
